unbind C-b
set -g prefix C-t
bind C-t send-prefix

set -g mouse on
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1

# Start window/panes in the current directory
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Move between windows
bind -r C-h previous-window
bind -r C-l next-window

# Split horizontally / vertically
bind / split-window -h -c "#{pane_current_path}"
bind . split-window -v -c "#{pane_current_path}"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g status on
set -g status-position top 

set -g status-style "bg=default,fg=default"
set -g window-status-current-style "fg=#EBDBB2"

set -g status-left-length 30
set -g status-right-length 50

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g status-justify centre

# Rename window
bind R command-prompt -p "Window name:" "rename-window '%%'"

# Rename session
bind S command-prompt -p "Session name:" "rename-session '%%'"
